"""empty message

Revision ID: a0ea667cb54c
Revises: d8750f4bf36b
Create Date: 2020-09-18 05:46:15.407310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0ea667cb54c'
down_revision = 'd8750f4bf36b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('transaction_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'transaction_date')
    # ### end Alembic commands ###
