"""empty message

Revision ID: a9db909e2330
Revises: 
Create Date: 2020-09-15 13:18:02.705050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9db909e2330'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cities', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('city_name', sa.String(length=80), nullable=False),
        sa.PrimaryKeyConstraint('id'))
    op.create_table('movies', sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=120), nullable=False),
                    sa.Column('release_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'users', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('phone_number', sa.String(length=10), nullable=False),
        sa.Column('password', sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint('id'), sa.UniqueConstraint('phone_number'))
    op.create_table(
        'cinemas', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('show_times',
                  postgresql.ARRAY(sa.String(length=8)),
                  nullable=True),
        sa.Column('city', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['city'],
            ['cities.id'],
        ), sa.PrimaryKeyConstraint('id'))
    op.create_table(
        'shows', sa.Column('movie_id', sa.Integer(), nullable=False),
        sa.Column('cinema_id', sa.Integer(), nullable=False),
        sa.Column('show_times', sa.String(length=8), nullable=False),
        sa.ForeignKeyConstraint(
            ['cinema_id'],
            ['cinemas.id'],
        ), sa.ForeignKeyConstraint(
            ['movie_id'],
            ['movies.id'],
        ), sa.PrimaryKeyConstraint('movie_id', 'cinema_id'))
    op.create_table(
        'tickets', sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('movie', sa.Integer(), nullable=False),
        sa.Column('cinema', sa.Integer(), nullable=False),
        sa.Column('show_time', sa.String(length=8), nullable=False),
        sa.Column('user', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ['cinema'],
            ['cinemas.id'],
        ), sa.ForeignKeyConstraint(
            ['movie'],
            ['movies.id'],
        ), sa.ForeignKeyConstraint(
            ['user'],
            ['users.id'],
        ), sa.PrimaryKeyConstraint('id'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tickets')
    op.drop_table('shows')
    op.drop_table('cinemas')
    op.drop_table('users')
    op.drop_table('movies')
    op.drop_table('cities')
    # ### end Alembic commands ###
