"""empty message

Revision ID: c0a6e5c87677
Revises: a9db909e2330
Create Date: 2020-09-15 17:49:15.351485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0a6e5c87677'
down_revision = 'a9db909e2330'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('date_from', sa.DateTime(), nullable=False))
    op.add_column('shows', sa.Column('date_to', sa.DateTime(), nullable=False))
    op.add_column('shows', sa.Column('no_of_seats', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'no_of_seats')
    op.drop_column('shows', 'date_to')
    op.drop_column('shows', 'date_from')
    # ### end Alembic commands ###
